[package]
name = "orion-dudect"
version = "0.1.0"
authors = ["brycx <brycx@protonmail.com>"]
edition = "2018"

[dependencies]
dudect-bencher = "0.4.0"
rand = "0.6"
orion = { git = "https://github.com/brycx/orion/", branch = "pteq-slice" }
clap = "2.25"
ctrlc = "3.1"
regex = "1"
rand_chacha = "0.1.1"

[features]
nightly = [ "orion/nightly" ]

[[bin]]
name = "secure_cmp"
path = "ct-bencher/secure_cmp.rs"

[[bin]]
name = "poly1305"
path = "ct-bencher/poly1305.rs"

[[bin]]
name = "newtype"
path = "ct-bencher/newtype.rs"

[[bin]]
name = "newtype_slice"
path = "ct-bencher/newtype_slice.rs"